Entropy Source Interface.
=========================
:author: Ben Marshall
:email: ben.marshall@bristol.ac.uk
:toc:
:lang: en

*This document describes the logic interface between the CPU and
an entropy source.*

== Overview

The core implements the `pollentropy` and `getnoise` pseudo instructions
from the (draft) RISC-V cryptography extension <<rvcrypto>>.
These instructions are aliases for CSR access instructions.

== Core Modifications

=== Decoder

No modifications to the decoder are needed.

=== Core Interfaces

A single new interface is added to the core, The `es` interface.
It consists of the following signals. Input/Output are from the
perspective of the _core_.

* O: `es_entropy_req` - set high when reading from `mentropy`.
* I: `es_entropy_opst[ 1:0]` - return sample status value.
* I: `es_entropy_data[15:0]` - return sample randomness.
* O: `es_noise_test` - Are we in noise test mode?
* O: `es_noise_wr` - Write to `mnoise` CSR.
* O: `es_noise_wdata[31:0]` - write data for `mnoise`.
* I: `es_noise_rdata[31:0]` - read data from `mnoise`.

=== CSR Module

The CSR module interfaces between normal CSR access requests from
the core, and the `es` interface described above.

Two new CSRs are implemented:

==== `0xF15` - `mentropy`

Read only, and accessed with the `pollentropy` pseudo instruction
via the `es_pollentropy_*` signals.

==== `0x7A9` - `mnoise`

Read/write and mostly vendor specific except for bit `31`, which indicates
we are in noise-capture mode.

The CSR module ensures that if `es_getnoise_noisetest` is set, then
`pollentropy` always returns `SEED=0` and `OPST=BIST`.

=== Misc issues.

- The `pollentropy` instruction may *only* be executed in machine mode,
  as per the specification.
  Execution in any other mode causes an invalid opcode exception.

- If the user programs (for example) the PMP registers to forbid
  access to `POLLENTROPY_PADDR`, then this will break the `pollentropy`
  instruction.

== References

[bibliography]
-- [[[rvcrypto]]] "Draft RISC-V Cryptography Extensions" https://github.com/scarv/riscv-crypto
